sonar.projectKey=xenios-backend
sonar.organization=adamasorho

# Project metadata
sonar.projectName=Xenios Backend
sonar.projectVersion=1.0

# GitHub repository binding
sonar.links.scm=https://github.com/adamasorho/xenios_github_actions

# Source code
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**

# Test coverage
sonar.go.coverage.reportPaths=coverage.out

# Go specific
sonar.go.tests.reportPaths=.
sonar.go.golangci-lint.reportPaths=.
