sonar.projectKey=xenios-mobile
sonar.organization=adamasorho

# Project metadata
sonar.projectName=Xenios Mobile
sonar.projectVersion=1.0

# GitHub repository binding
sonar.links.scm=https://github.com/adamasorho/xenios_github_actions

# Source code
sonar.sources=src,../../packages
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/node_modules/**,**/android/**,**/ios/**

# TypeScript/JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
